services:
  pmmp:
    container_name: ${CONTAINER_NAME:-pmmp}
    image: pmmp/pocketmine-mp:latest
    ports:
      - ${PORT:-19132}:19132/udp
      - ${QUERY_PORT:-19132}:19132
    volumes:
      - .:/plugins/${PLUGIN_NAME:-MyPlugin}
      - ./data:/data
      - plugins:/plugins
    environment:
      - POCKETMINE_PLUGINS=DevTools

volumes:
  plugins: